#!/bin/sh
#Keyboard layout mgmt requires xkb-switch -> https://github.com/ierton/xkb-switch
#by Jonathan Becktor
#GG
case $BLOCK_BUTTON in
  3) xkb-switch -n;; # right click, mute/unmute
esac

xkb-switch
