#!/bin/sh
# Based on http //openweathermap.org/current

API_KEY="f68b1577ff0f46e8c022e90eb53e76cd"

# Check on http://openweathermap.org/find
CITY_ID="2618425"

URGENT_LOWER=0
URGENT_HIGHER=30

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""
ICON_NA=""
SYMBOL_CELSIUS="°"
WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")

WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')



if [[ -z $WEATHER_MAIN ]]; then
    echo $ICON_NA
    echo ""
    echo "#FF3F00"

elif [[ $WEATHER_MAIN = *Clear* ]]; then
    echo $ICON_SUNNY $WEATHER_TEMP$SYMBOL_CELSIUS
    echo $WEATHER_TEMP$SYMBOL_CELSIUS
    echo '#FFF600'

elif [[ $WEATHER_MAIN = *Snow* ]]; then
    echo $ICON_SNOW $WEATHER_TEMP$SYMBOL_CELSIUS
    echo $WEATHER_TEMP$SYMBOL_CELSIUS
    echo "#4F8AFF"

elif [[ $WEATHER_MAIN = *Rain* ]] || [[ $WEATHER_MAIN = *Drizzle* ]]; then
    echo $ICON_RAINY $WEATHER_TEMP$SYMBOL_CELSIUS
    echo $WEATHER_TEMP$SYMBOL_CELSIUS
    echo "#4F8AFF"

elif [[ $WEATHER_MAIN = *Storm* ]]; then
    echo $ICON_STORM $WEATHER_TEMP$SYMBOL_CELSIUS
    echo $WEATHER_TEMP$SYMBOL_CELSIUS
    echo '#FFF600'

elif [[ $WEATHER_MAIN = *Cloud* ]]; then
    echo $ICON_CLOUDY $WEATHER_TEMP$SYMBOL_CELSIUS
    echo $WEATHER_TEMP$SYMBOL_CELSIUS
    echo "#4F8AFF"

elif [[ $WEATHER_MAIN = *Clear* ]]; then
    echo $ICON_SUNNY $WEATHER_TEMP$SYMBOL_CELSIUS
    echo $WEATHER_TEMP$SYMBOL_CELSIUS
    echo "#4F8AFF"

elif [[ $WEATHER_MAIN = *Fog* ]] || [[ $WEATHER_MAIN = *Mist* ]]; then
    echo $ICON_FOG $WEATHER_TEMP$SYMBOL_CELSIUS
    echo $WEATHER_TEMP$SYMBOL_CELSIUS
    echo "#C0C0C0"

else
    echo $WEATHER_MAIN $WEATHER_TEMP$SYMBOL_CELSIUS
    echo $WEATHER_MAIN $WEATHER_TEMP$SYMBOL_CELSIUS
    echo '#FFF600'
fi


#if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
# exit 33
#fi
